services:
- type: background
  name: telegram-bot
  runtime: python
  plan: free
  buildCommand: ""
  startCommand: "python bot.py"
  envVars:
  - key: TELEGRAM_BOT_TOKEN
    sync: false
  - key: ADMIN_IDS
    sync: false
  - key: DEFAULT_LINK
    sync: false
