services:
- type: web # Or "worker" if no HTTP route is needed
  name: telegram-bot
  runtime: python
  plan: free
  buildCommand: "pip install -r requirements.txt"
  startCommand: "python bot.py"
  envVars:
  - key: TELEGRAM_BOT_TOKEN
    sync: false
  - key: ADMIN_IDS
    sync: false
  - key: DEFAULT_LINK
    sync: false
